from django.conf import settings

BASE_URL = settings.STATS_BASE_URL
BASE_HOST = settings.STATS_BASE_HOST
BASE_PATH = settings.STATS_BASE_PATH

IMAGE_WIDTH = settings.STATS_IMAGE_WIDTH
WIDTH = settings.STATS_WIDTH
HEIGHT = settings.STATS_HEIGHT

RRD_PREFIX = settings.STATS_RRD_PREFIX
GRAPH_PREFIX = settings.STATS_GRAPH_PREFIX

FONT = settings.STATS_FONT

BAR_BORDER_COLOR = settings.STATS_BAR_BORDER_COLOR
BAR_BG_COLOR = settings.STATS_BAR_BG_COLOR
