#coding=utf8
from django.conf import settings
from synnefo.lib import parse_base_url, join_urls
from synnefo.lib.services import get_service_prefix

BASE_URL = settings.PITHOS_BASE_URL
BASE_HOST = settings.PITHOS_BASE_HOST
BASE_PATH = settings.PITHOS_BASE_PATH

ASTAKOS_BASE_URL = settings.ASTAKOS_BASE_URL
ASTAKOS_BASE_HOST = settings.ASTAKOS_BASE_HOST,
ASTAKOS_BASE_PATH = settings.ASTAKOS_BASE_PATH

synnefo_services = settings.SYNNEFO_SERVICES

PITHOS_PREFIX = get_service_prefix(synnefo_services, 'pithos_object-store')
PUBLIC_PREFIX = get_service_prefix(synnefo_services, 'pithos_public')
UI_PREFIX = get_service_prefix(synnefo_services, 'pithos_ui')

ASTAKOS_ACCOUNTS_PREFIX = get_service_prefix(synnefo_services, 'astakos_account')
ASTAKOS_VIEWS_PREFIX = get_service_prefix(synnefo_services, 'astakos_ui')
ASTAKOS_KEYSTONE_PREFIX = get_service_prefix(synnefo_services, 'astakos_identity')

BASE_ASTAKOS_PROXY_PATH = getattr(settings, 'PITHOS_BASE_ASTAKOS_PROXY_PATH',
                                  ASTAKOS_BASE_PATH)
BASE_ASTAKOS_PROXY_PATH = join_urls(BASE_PATH, BASE_ASTAKOS_PROXY_PATH)
BASE_ASTAKOS_PROXY_PATH = BASE_ASTAKOS_PROXY_PATH.strip('/')


SERVICE_TOKEN = settings.PITHOS_SERVICE_TOKEN

COOKIE_NAME = settings.PITHOS_ASTAKOS_COOKIE_NAME

ASTAKOSCLIENT_POOLSIZE = settings.PITHOS_ASTAKOSCLIENT_POOLSIZE
BACKEND_POOL_ENABLED = settings.PITHOS_BACKEND_POOL_ENABLED
BACKEND_POOL_SIZE = settings.PITHOS_BACKEND_POOL_SIZE

BACKEND_DB_MODULE = settings.PITHOS_BACKEND_DB_MODULE
BACKEND_BLOCK_MODULE = settings.PITHOS_BACKEND_BLOCK_MODULE

BACKEND_DB_CONNECTION = settings.PITHOS_BACKEND_DB_CONNECTION
BACKEND_BLOCK_PATH = settings.PITHOS_BACKEND_BLOCK_PATH
BACKEND_BLOCK_SIZE = settings.PITHOS_BACKEND_BLOCK_SIZE
BACKEND_HASH_ALGORITHM = settings.PITHOS_BACKEND_HASH_ALGORITHM

UPDATE_MD5 = settings.PITHOS_UPDATE_MD5

BACKEND_VERSIONING = settings.PITHOS_BACKEND_VERSIONING
BACKEND_FREE_VERSIONING = settings.PITHOS_BACKEND_FREE_VERSIONING

RADOS_STORAGE = settings.PITHOS_RADOS_STORAGE
RADOS_POOL_BLOCKS = settings.PITHOS_RADOS_POOL_BLOCKS
RADOS_POOL_MAPS = settings.PITHOS_RADOS_POOL_MAPS

PROXY_USER_SERVICES = settings.PITHOS_PROXY_USER_SERVICES

PUBLIC_URL_SECURITY =  settings.PITHOS_PUBLIC_URL_SECURITY
PUBLIC_URL_ALPHABET =  settings.PITHOS_PUBLIC_URL_ALPHABET

API_LIST_LIMIT = settings.PITHOS_API_LIST_LIMIT

#
# Obsolete settings, these should go away along with the relevant code.
#

BACKEND_BLOCK_UMASK = settings.PITHOS_BACKEND_BLOCK_UMASK

BACKEND_QUEUE_MODULE = settings.PITHOS_BACKEND_QUEUE_MODULE
BACKEND_QUEUE_HOSTS = settings.PITHOS_BACKEND_QUEUE_HOSTS
BACKEND_QUEUE_EXCHANGE = settings.PITHOS_BACKEND_QUEUE_EXCHANGE

BACKEND_ACCOUNT_QUOTA = settings.PITHOS_BACKEND_ACCOUNT_QUOTA
BACKEND_CONTAINER_QUOTA = settings.PITHOS_BACKEND_CONTAINER_QUOTA

TRANSLATE_UUIDS = settings.PITHOS_TRANSLATE_UUIDS
