snf-cyclades-app/synnefo/cyclades/ui/static usr/share/synnefo/static/ui
snf-cyclades-app/synnefo/cyclades/helpdesk/static/css usr/share/synnefo/static/helpdesk
snf-cyclades-app/synnefo/cyclades/helpdesk/static/img usr/share/synnefo/static/helpdesk
snf-cyclades-app/synnefo/cyclades/helpdesk/static/js usr/share/synnefo/static/helpdesk
snf-cyclades-app/conf/* etc/synnefo
snf-cyclades-app/synnefo/cyclades/tools/ usr/lib/synnefo/
