from synnefo import settings

USER_MODEL = settings.OAUTH2_USER_MODEL
ENDPOINT_PREFIX = settings.OAUTH2_ENDPOINT_PREFIX
TOKEN_ENDPOINT = settings.OAUTH2_TOKEN_ENDPOINT
AUTHORIZATION_ENDPOINT = settings.OAUTH2_AUTHORIZATION_ENDPOINT
AUTHORIZATION_CODE_LENGTH = settings.OAUTH2_AUTHORIZATION_CODE_LENGTH
TOKEN_LENGTH = settings.OAUTH2_TOKEN_LENGTH
TOKEN_EXPIRES = settings.OAUTH2_TOKEN_EXPIRES
MAXIMUM_ALLOWED_REDIRECT_URI_LENGTH = \
    settings.OAUTH2_MAXIMUM_ALLOWED_REDIRECT_URI_LENGTH
